version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/bootcamp-app
    ports:
      - 3035:3035
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bootcamp-app
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpacker
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
